// Code generated by sqlc. DO NOT EDIT.

package db

import ()

type Account struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Auth     int32  `json:"auth"`
}
