name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: actions-setup-mysql
      uses: shogo82148/actions-setup-mysql@v1.3.2
      with:
        user: thomas
        password: 123456
    - run: mysql -uroot -h 127.0.0.1 -e 'CREATE DATABASE IF NOT EXISTS `iam`'
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
